################################################################################
require("rake/testtask")
require("rspec/core/rake_task")

################################################################################
task(:default => [:test])

################################################################################
Rake::TestTask.new do |t|
  t.test_files = FileList['*/*_test.rb']
  t.warning    = true
end

################################################################################
RSpec::Core::RakeTask.new do |t|
  t.pattern = FileList['*/*_spec.rb']
end
